### ISSUE TITLE
Closing MessageBox with buttons by ESC key causing ArgumentException 

### ISSUE THREAD

**Issue by ijklam** [DieselMeister/Terminal.Gui.Elmish#18]
### Description

When a MessageBox with buttons is closed by ESC key, an ArgumentException will be thrown. 

### Repro steps

1. Install Terminal.Gui.Elmish 2.0.164-preview1 from nuget

1. Open a MessageBox with buttons
    ``` fsharp
    Dialogs.messageBox 10 10 "Title" "Content" ["OK"]
    ```
2. Press the ESC key

### Expected behavior

No Exception will be thrown.

### Actual behavior

An ArgumentException will be thrown with "Input must be non-negative (Parameter 'n')"

![image](https://user-images.githubusercontent.com/43789618/185722529-9b6a8d10-eff9-4c92-bdc1-89b3fd2baa21.png)

**Comment by Hardt-Coded** [comment]
Hi. I fixed the problem. Also I moved to the latest Terminal.Gui version 1.72. 

https://www.nuget.org/packages/Terminal.Gui.Elmish/2.0.172

**Comment by ijklam** [comment]
Thank you.
