### ISSUE TITLE
Parameter type of tableView.onCellActivated and tableView.onSelectedCellChanged is wrong

### ISSUE THREAD

**Issue by ijklam** [DieselMeister/Terminal.Gui.Elmish#19]
### Description

Parameter type of `tableView.onCellActivated` is wrong. The function should accept a `(Terminal.Gui.TableView.CellActivatedEventArgs -> unit)`, but currently accepts a `(unit -> unit)`. This will raise a runtime exception.

The situation when calling `tableView.onSelectedCellChanged` is same.

### Expected behavior

Program will run without exception

### Actual behavior

An exception will be thrown.

![image](https://user-images.githubusercontent.com/43789618/185759051-e3393129-c3e9-43c6-a75c-a8fc4d2e040f.png)

![image](https://user-images.githubusercontent.com/43789618/185759086-e3252d2c-4790-4770-9de9-097533a492e5.png)

**Comment by Hardt-Coded** [comment]
fix is published. Thanks for finding these error! :D 

https://www.nuget.org/packages/Terminal.Gui.Elmish/2.1.172
