### ISSUE TITLE
Text field cursor behaviour

### ISSUE THREAD

**Issue by misterspeedy** [DieselMeister/Terminal.Gui.Elmish#2]
### Description

When a text field is edited with the cursor position somewhere other than the end of the field, the model-updating process ends up moving the text cursor to the end of the field.

### Repro steps

Please provide the steps required to reproduce the problem

1. Run the demo

2. Go to the `TextFields` section

3. Click in the middle of the `Text` field.

4. Insert a character.

### Expected behavior

Text cursor should remain after the last inserted character.

### Actual behavior

Text cursor is now at the end of the field.

### Known workarounds

This is an issue which affects other Elmish incarnations, because the `OnChanged` event of a field triggers a message, which triggers a model change, which changes the field value.  In Fable browser apps (if I recall correctly) this can be worked around by setting the `DefaultValue` property instead of the `Value` property. It would be great to have a similar workaround here.

### Related information 

* Operating system
* Branch
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by Hardt-Coded** [comment]
Added a pull request to the Terminal.Gui project to get the proper preconditions to fix the bug inside my code.

https://github.com/migueldeicaza/gui.cs/pull/187

**Comment by Hardt-Coded** [comment]
The Pull Request on Miguel's side ia already merged! Waiting for a new nuget version.

**Comment by misterspeedy** [comment]
Amazing. Thanks!

**Comment by Hardt-Coded** [comment]
fixed :)
