### ISSUE TITLE
TabView Tabs

### ISSUE THREAD

**Issue by sheridanchris** [DieselMeister/Terminal.Gui.Elmish#26]
### Description
Defining individual tabs for a tab view doesn't seem to be implemented. I'd like to create a PR to implement this and am wondering what the API might look like.

I was thinking of something like this:

```fs
View.tabView [
  tabView.tabs [
    tabView.tab [
      tab.title "Tab 1"
      tab.view [
        View.label [ label.text "Hello, World!" ]
      ]
    ]
    tabView.tab [
      tab.title "Tab 2"
      tab.view [
        View.label [ label.text "Hello, World!" ]
      ]
    ]
  ]
]
```

I see that `prop.ref` exists to reference the TabView element directly and add tabs that way but I think a feliz-style definition would be quite nice to add.

**Comment by Hardt-Coded** [comment]
Looks good! Thank you.  :)

**Comment by Hardt-Coded** [comment]
The api is not complete. I think I am missing also the proper implementation of the menu stuff. I am currently busy with work. So again thank you for doing this!
