### ISSUE TITLE
Example shows quit method which doesn't exist

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [DieselMeister/Terminal.Gui.Elmish#3]
### Description

The example says there should be a `Program.quit` but it does not exist

### Repro steps

see https://github.com/ImaginaryDevelopment/terminalpad/tree/ed6da4945b341cd5d552a8bc6986b17a02371f42

### Expected behavior

I expect calling `Program.quit()` to be able to compile

### Actual behavior

no compilation

### Related information 

* Operating system - Mac OSX
* Branch - master 
* .NET Runtime, CoreCLR or Mono Version
 - `dotnet --version` : 2.2.105
* Performance information, links to performance testing scripts

**Comment by Hardt-Coded** [comment]
Sorry, Miguel (Terminal.Gui) did deploy his corrected version (0.23.0) earlier today, so I am now able to deploy a new version (0.1.3) where you get the need functions.

**Comment by Hardt-Coded** [comment]
Released nuget version 0.1.3

Now Program.quit should be available. Please try.

**Comment by Hardt-Coded** [comment]
so no further response to this issue, I close it.
