### ISSUE TITLE
Suggest using byte literals in example

### ISSUE THREAD

**Issue by jbtule** [DieselMeister/Terminal.Gui.Elmish#6]
Not an issue, and isn't being used yet in the example, but f# has some many nice literal features I thought i'd point out

https://github.com/DieselMeister/Terminal.Gui.Elmish/blob/64089e43db4c8efa2b6b372e42fc6779db15957e/examples/ElmishConsoleTest01/Program.fs#L118-L122
Could be literals in hex or dec, or even binary
```
let ms = new MemoryStream([| 
     0xAuy; 0x14uy; 0x1Euy; 0x32uy; 0x32uy 
     10uy; 20uy; 30uy; 40uy; 50uy
     0b1010uy; 0b10100uy; 0b11110uy; 0b101000uy; 0b110010uy
 |]) 
```

**Comment by Hardt-Coded** [comment]
nice, but this was the first try example app, that has no purpose any more. So the next time, I will delete or remove any commented und not functional code in this project, and let display only the ASCII Logo :). But thanks a lot for the Info. Nice!
